Fixes Error "Cannot find module"
Webpack cannot find module because it points to non-existing index.js
```
Runtime Error
Cannot find module "ng2-gridstack"
Stack
Error: Cannot find module "ng2-gridstack"
    at Object.257 (http://localhost:8100/build/main.js:371:7)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.252 (http://localhost:8100/build/main.js:354:70)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)
    at http://localhost:8100/build/main.js:1:1
```